# GitHub Pages configuration
theme: minima
plugins:
  - jekyll-feed

# Site configuration
title: Python Cheat Sheet
description: A Python reference guide covering essential syntax, concepts, and best practices

# Optional configuration
show_downloads: false

# GitHub Pages settings
repository: geniuslounge/python-cheat-sheet