# GitHub Pages configuration
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Site configuration
title: Python Cheat Sheet
description: A Python reference guide covering essential syntax, concepts, and best practices

# Optional configuration
show_downloads: false

# GitHub Pages settings
repository: geniuslounge/python-cheat-sheet