# GitHub Pages configuration for Modernist theme
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme

# Site configuration
title: Python Cheat Sheet
description: A Python reference guide covering essential syntax, concepts, and best practices

# Optional configuration
show_downloads: false

# GitHub Pages settings
github:
  repository_url: https://github.com/geniuslounge/python-cheat-sheet/